### PR TITLE
Note about adding time stamps to community call recordings

### PR DESCRIPTION
**Pull request by GBKS**
And a minor copy fix to the design review call doc.

### CODE REVIEW

**Review by sbddesign — APPROVED** [review]
This just adds more work to do every time I upload a call, but you know I love more work. 

LGTM.

**Review by Bosch-0 — APPROVED** [review]
LGTM, you can put this stamps in the video itself on YouTube instead of sharing them as plaintext 

https://www.youtube.com/watch?v=yfEdhlBuxCU

**Comment by GBKS** [comment]
@Bosch-0 I started adding the time stamps to both the YouTube and BitcoinTV videos, as well as the summary comment on the call issue. That way, the time stamps also serve as the call summary and people don't have to click through.

@sbddesign it is an annoying bit of extra work, but it does make the videos much more accessible. We should start tag-teaming on all our calls more often, with one person taking notes and writing down time stamps as the call happens. That might ease some of the follow-up work.

**Comment by sbddesign** [comment]
> ...with one person taking notes and writing down time stamps as the call happens.

Yeah, that would be cool. However, the time readout on Jitsi usually corresponds to how long the call has been filled with people and not how long the recording has happened. For example, if we chatted for 15 minutes before the recording, the timestamp will be skewed. Not sure the timestamp in the video reflects this.
  
It would be super cool if there was a Jitsi plugin for marking timestamps when recording. Just a simple "mark this" button.

**Review by danielnordh — APPROVED** [review]
Good to go

**Pull request merged**
